
ALTER TABLE `esms_teams` MODIFY COLUMN `captain`  bigint(12) NULL AFTER `name`;
 
INSERT INTO `esms_users` (username, password, email, active) VALUES
    ("user1","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user2","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user3","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user4","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user5","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user6","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user7","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user8","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user9","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user10","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user11","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user12","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user13","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user14","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user15","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user16","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user17","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user18","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user19","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user20","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user21","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user22","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user23","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user24","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user25","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user26","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user27","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user28","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user29","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user30","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user31","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user32","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user33","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user34","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user35","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user36","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user37","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user38","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user39","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("user40","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1),
    ("admin","$2y$10$KRbzptXNmuwQwWyFmNaHN.bwtvIFty9v6cK5PeRHq.HvKMRXNYvfC","mail@bla.com", 1);

INSERT INTO `esms_teams` (tag,name,facebook,twitter,website,about,avatar,country) VALUES
    ("FNC","Fnatic","www.fb.com/fnatik","www.twitter.com/fnatik","www.fnatic.com","In the 2014 Spring Split, Fnatic saw monumental successes and failures, but ended on a high-note, taking first place for the third split in a row. Following a humbling performance at All-Star, only defeating TPA, Fnatic will take plenty of lessons into the summer split.", "fnatic.jpg", "EU"),
    ("GMB","Gambit Gamming","www.fb.com/gmb","www.twitter.com/gmb","www.gambit.com","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500", "gambit.jpg", "Russia"),
    ("C9","Cloud 9","www.fb.com/fnatik","www.twitter.com/fnatik","www.fnatic.com","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500", "c9.jpg", "United States"),
    ("Dig","Dignitas","www.fb.com/fnatik","www.twitter.com/fnatik","www.fnatic.com","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500", "dig.jpt", "Sweden"),
    ("CLG","Counter Logic Gamming","www.fb.com/fnatik","www.twitter.com/fnatik","www.fnatic.com","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500.", "clg.jpg", "EU"),
    ("Na'Vi","Natus Vincere","www.fb.com/navi","www.twitter.com/navi","www.navi.com","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500", "navi.jpg", "Ukraine"),
    ("empr","Empire","www.fb.com/empire","www.twitter.com/empire","www.empire.com","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500", "empr.jpg", "Russia"),
    ("ef","Elfak","www.fb.com/ef","www.twitter.com/ef","www.ef.com","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500", "elf.jpg", "Serbia");

INSERT INTO `esms_players` (userID,name,last_name,nick,teamID,avatar,bio,country,facebook,twitter,website,position) VALUES
    (1,"Enrique","Mendez","xPeke",1, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Spain","fb.com/123123","tw.com/123213","www.fntic.com", 'Mid'), 
    (2,"Soz","Perez","sOAZ",1, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Spain","fb.com/123123","tw.com/123213","www.fntic.com", 'Carry'), 
    (3,"YEz","Zerez","YellOwStaR",1, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Spain","fb.com/123123","tw.com/123213","www.fntic.com", 'Support'), 
    (4,"Cy","Cijaez","Cyanide",1, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Spain","fb.com/123123","tw.com/123213","www.fntic.com", 'Jungler'), 
    (5,"Rek","Perez","Rekkles",1, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Sweedish","fb.com/123123","tw.com/123213","www.fntic.com", 'Mid'), 
    (6,"Corki","Nami","puzu",1, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Spain","fb.com/123123","tw.com/123213","www.fntic.com", 'Carry'), 
    (7,"Weed","Master","Darien",2, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Russia","fb.com/123123","tw.com/123213","www.gmb.com", 'Support'), 
    (8,"Lee Sin","Evelyn","Diamond",2, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Russia","fb.com/123123","tw.com/123213","www.gmb.com", 'Carry'), 
    (9,"Alex","Ichatovin","AlexIch",2, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Russia","fb.com/123123","tw.com/123213","www.gmb.com", 'Support'), 
    (10,"Caitlyn","Lucian","Genja",2, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Russia","fb.com/123123","tw.com/123213","www.gmb.com", 'Mid'), 
    (11,"Thresh","Annie","EdWard",2, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Russia","fb.com/123123","tw.com/123213","www.gmb.com", 'Jungler'), 
    (12,"Daerek","Hart","LemonNation",3, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Jungler'), 
    (13,"Zachary","Scuderi","Sneaky",3, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Mid'), 
    (14,"William","Hartman","Meteos",3, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Carry'), 
    (15,"An","Le","Balls",3, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Mid'), 
    (16,"Hai","Hai","Lam",3, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Support'), 
    (17,"Darshan","ZionSpartan","Upadhyaha",4, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Jungler'), 
    (18,"Alberto","Rengifo","Crumbzz",4, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Carry'), 
    (19,"Danny","Le","Shiphtur",4, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Support'), 
    (20,"Michael","Santana","Imaqtpie",4, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com",'Jungler'), 
    (21,"Alan","Nguyen","KiWiKid",4, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com",'Support'), 
    (22,"Yiliang","Peng","Doublelift",5, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Carry'), 
    (23,"Zaqyeru","Black","Aphromoo",5, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Support'), 
    (24,"Austin","Shin","Link",5, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Mid'),
    (25,"Marcel","Fledkamp","dexter",5, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Offlaner'), 
    (26,"Shin","Woo-Yeong","Seraph",5, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","USA","fb.com/123123","tw.com/123213","www.c9.com", 'Carry'),
    (27,"Oleksandar","Dashkevych","XBOCT",6, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Ukraine","fb.com/123123","tw.com/123213","www.c9.com", 'Carry' ),
    (28,"Danylo","Ishutin","Dendi",6, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Ukraine","fb.com/123123","tw.com/123213","www.c9.com", 'Mid' ),
    (29,"Hlib","Lipatnikov","Funn1k",6, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Ukraine","fb.com/123123","tw.com/123213","www.c9.com", 'Offlaner' ),
    (30,"Clement","Ivanov","Puppey",6, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Estonia","fb.com/123123","tw.com/123213","www.c9.com", 'Support' ),
    (31,"Kuro Salehi","Takhasomi","KuroKy",6, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Germany","fb.com/123123","tw.com/123213","www.c9.com", 'Support' ),
    (32,"Airat","Gaziev","Silent",7, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Russia","fb.com/123123","tw.com/123213","www.c9.com", 'Carry' ),
    (33,"Roman","Fominok ","Resolut1on",7, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Ukraine","fb.com/123123","tw.com/123213","www.c9.com", 'Mid' ),
    (34,"Andrew","Chipenko","Mag~",7, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Ukraine","fb.com/123123","tw.com/123213","www.c9.com", 'Offlaner' ),
    (35,"Ivan","Skorokhod","VANSKOR",7, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Russia","fb.com/123123","tw.com/123213","www.c9.com", 'Support' ),
    (36,"Andrey","Bondarenko","ALWAYSWANNAFLY",7, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Ukraine","fb.com/123123","tw.com/123213","www.c9.com", 'Support' ),
    (37,"Jonathan","Berg","Loda",8, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Sweden","fb.com/123123","tw.com/123213","www.c9.com", 'Offlaner' ),
    (38,"Bojan","Adamovic","boki",8, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Serbia","fb.com/123123","tw.com/123213","www.c9.com", 'Support' ),
    (39,"Mario","Zalac","zalac",8, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Serbia","fb.com/123123","tw.com/123213","www.c9.com", 'Support' ),
    (40,"Milutin","Stankovic","lordmilutin",8, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Serbia","fb.com/123123","tw.com/123213","www.c9.com", 'Mid' ),
    (41,"Dejan","Stosic","Dejan7",8, NULL, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500","Serbia","fb.com/123123","tw.com/123213","www.c9.com", 'Carry' );
